fix(test): Set RUST_MIN_STACK in config.toml
Without this, locally the test fails with:

```
thread 'branch_merge_with_blob_columns_preserves_blob_data' (439132251) has overflowed its stack
fatal runtime error: stack overflow, aborting
error: test failed, to rerun pass `-p omnigraph-engine --test branching`

Caused by:
  process didn't exit successfully: `/Users/dhanush/mr/omnigraph/target/debug/deps/branching-81832813ea3c1dab` (signal: 6, SIGABRT: process abort signal)
```

We already set 16777216 (16Mb) in CI, so this should be a sane default for
local dev as well.